### ISSUE TITLE
when used for opera-developer and opera-beta breaks apt-get install

### ISSUE THREAD

**Issue by dragus0** [Ld-Hagen/fix-opera-linux-ffmpeg-widevine#10]
hello, great work this fixed the issue

the problem, as described in the title, i use opera developer

i selected to  use the script whenever opera si updated or installed thus the following apt commands were not working
sudo apt install ffmpeg
sudo apt install opera-beta
sudo apt install vlc
sudo apt install opera-stable

all were failing with Problem executing scripts DPkg::Pre-Invoke so i had to remove the script from apt dir

Noticed this err while installing 
![Kazam_screenshot_00000](https://user-images.githubusercontent.com/62744978/193273690-819118fe-f896-470b-8f94-e948dd281aa2.png)
received this when using for opera developer and opera but i don t think they are important 
![Kazam_screenshot_00005](https://user-images.githubusercontent.com/62744978/193274500-b980a359-2629-4e93-96fd-61e05e8db785.png)

anyway thank you and have a nice day

**Comment by Ld-Hagen** [comment]
Hi. For opera-beta you may replace "opera" with "opera-beta" (or "opera-developer" for opera-developer) in there
`readonly OPERA_DIR=$(dirname $(readlink -f $(which opera)))` (scripts/fix-opera.sh)
`DPkg::Pre-Invoke {"stat -c %Z $(readlink -f $(which opera)) > /tmp/opera.timestamp";};` (scripts/99fix-opera)
`DPkg::Post-Invoke {"if [ `stat -c %Z $(readlink -f $(which opera))` -ne `cat /tmp/opera.timestamp` ]; then /root/.scripts/fix-opera.sh; fi; rm /tmp/opera.timestamp";};` (scripts/99fix-opera)

But it still may brake your installation if testing version requires newer version of libffmpeg.so than stable one.

**Comment by dragus0** [comment]
thanks 4 the quick response

it's ok i ll just use opera

i'm just wondering the err happens if no opera is installed or just a different opera


anyway maybe a check would be good in the script if conditions are not met it should abort, just a suggerstion

anyway thanx again 4 the great work. works great with opera-stable

feel free to close the issue.

**Comment by oliveselow** [comment]
> Hi. For opera-beta you may replace "opera" with "opera-beta" (or "opera-developer" for opera-developer) in there `readonly OPERA_DIR=$(dirname $(readlink -f $(which opera)))` (scripts/fix-opera.sh) `DPkg::Pre-Invoke {"stat -c %Z $(readlink -f $(which opera)) > /tmp/opera.timestamp";};` (scripts/99fix-opera) `DPkg::Post-Invoke {"if [ `stat -c %Z (readlink−f(which opera))`-ne`cat /tmp/opera.timestamp` ]; then /root/.scripts/fix-opera.sh; fi; rm /tmp/opera.timestamp";};` (scripts/99fix-opera)
> 
> But it still may brake your installation if testing version requires newer version of libffmpeg.so than stable one.
