### ISSUE TITLE
basename: missing operand error

### ISSUE THREAD

**Issue by qolb** [Ld-Hagen/fix-opera-linux-ffmpeg-widevine#12]
Sorry, I am not very proficient in this and hope I ask in the right place:
When I run the script, I get "basename: missing operand ... Failed to get ffmpeg download URL. Exiting ..."
How to fix this?
Thanks in advance for your response!

**Comment by Ld-Hagen** [comment]
Try now, I guess it should work

**Comment by qolb** [comment]
Unfortunatley not.  Same error message.  I run Debian 11, if that is of an help.
In any case, thank you for your response!

**Comment by Ld-Hagen** [comment]
Still shows "Failed to get ffmpeg download URL. Exiting ..."? Make sure you've updated scripts (cd to repo directory, git pull and run install.sh again). 
![Output with yesterday's changes](https://user-images.githubusercontent.com/34414986/210169564-f665a651-3320-4d22-85cc-75f93c85177d.png)

**Comment by qolb** [comment]
Thanks for your help!  This is what I get:
![Screenshot](https://user-images.githubusercontent.com/121633113/210175376-8bfc438e-9e10-4256-a0b5-3461bf851195.png)

**Comment by Ld-Hagen** [comment]
It seems you have made some local changes, so you can't pull changes from repo.
Run **git reset –hard** and **git clean -fxd** before **git pull** or simply remove local copy and clone it again.

**Comment by qolb** [comment]
Thanks a lot, that did the trick!!!

**Comment by Ld-Hagen** [comment]
G

**Comment by oliveselow** [comment]
Like.....!

**Comment by oliveselow** [comment]
> Try now, I guess it should work There still should be a warning, but it's cause of disabling of https://github.com/nwjs-ffmpeg-prebuilt/nwjs-ffmpeg-prebuilt source of ffmpeg to prevent incompatibility of ffmpeg and Opera last versions that happent time to time.

**Comment by oliveselow** [comment]
> Try now, I guess it should work There still should be a warning, but it's cause of disabling of https://github.com/nwjs-ffmpeg-prebuilt/nwjs-ffmpeg-prebuilt source of ffmpeg to prevent incompatibility of ffmpeg and Opera last versions that happent time to time.
