### ISSUE TITLE
Custom libffmpeg.so file should go in lib_extra folder

### ISSUE THREAD

**Issue by burnout426** [Ld-Hagen/fix-opera-linux-ffmpeg-widevine#2]
If I read fix-opera.sh correctly, you're overwriting Opera's default "libffmpeg.so" that's in "/usr/lib/x86_64-linux-gnu/opera/" instead of leaving it alone and putting the custom one (one with support for proprietary codecs you fetch)  in "/usr/lib/x86_64-linux-gnu/opera/lib_extra/" (after you make sure the "lib_extra" folder exists).

If so, while that will work, your custom libffmpeg.so can get overwritten if Opera is updated or Opera updates its default libffmpeg.so for some reason. If you put the custom one in the lib_extra folder (per Opera's recommendations), it'll survive an update and you'll only have to update the file when Opera updates to a new major version of Chromium. Otherwise, you might have to re-run fix-opera.sh after each time you update Opera.

**Comment by Ld-Hagen** [comment]
It seems that Opera works well with libffmpeg.so placed in lib_extra, so I'll made changes to place it in that folder.

As for second part - the script made to re-run after each update of Opera.

**Comment by burnout426** [comment]
Sounds good.

**Comment by oliveselow** [comment]
> If I read fix-opera.sh correctly, you're overwriting Opera's default "libffmpeg.so" that's in "/usr/lib/x86_64-linux-gnu/opera/" instead of leaving it alone and putting the custom one (one with support for proprietary codecs you fetch) in "/usr/lib/x86_64-linux-gnu/opera/lib_extra/" (after you make sure the "lib_extra" folder exists).
> 
> If so, while that will work, your custom libffmpeg.so can get overwritten if Opera is updated or Opera updates its default libffmpeg.so for some reason. If you put the custom one in the lib_extra folder (per Opera's recommendations), it'll survive an update and you'll only have to update the file when Opera updates to a new major version of Chromium. Otherwise, you might have to re-run fix-opera.sh after each time you update Opera.
