### ISSUE TITLE
Got error on running fix script: $OPERA_WIDEVINE_DIR is empty

### ISSUE THREAD

**Issue by mubat** [Ld-Hagen/fix-opera-linux-ffmpeg-widevine#20]
Can't fix Opera got error with unknown variable
Why it is empty?

OS: Linux Mint 21.2 Cinnamon

> ~:$ sudo apt reinstall opera-stable 
The following packages will be REINSTALLED:
  opera-stable 
0 packages upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 8 not upgraded.
Need to get 106 MB of archives. After unpacking 0 B will be used.
Get: 1 https://deb.opera.com/opera-stable stable/non-free amd64 opera-stable amd64 102.0.4880.51 [106 MB]
Fetched 106 MB in 10s (10,6 MB/s)                                                                                                   
Preconfiguring packages ...
(Reading database ... 572003 files and directories currently installed.)
Preparing to unpack .../opera-stable_102.0.4880.51_amd64.deb ...
Unpacking opera-stable (102.0.4880.51) over (102.0.4880.51) ...
Setting up opera-stable (102.0.4880.51) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu3) ...
Processing triggers for shared-mime-info (2.1-2) ...
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...
Processing triggers for desktop-file-utils (0.26+mint3+victoria) ...
Getting download links...
Downloading files...
/tmp/opera-fix/ffmpeg.zip        100%[==========================================================>]   4,97M  8,15MB/s    in 0,6s    
/tmp/opera-fix/widevine.zip      100%[==========================================================>]   8,04M  8,01MB/s    in 1,0s    
Extracting files...
Doing opera
grep: (standard input): binary file matches
dirname: missing operand
Try 'dirname --help' for more information.
Removing old libraries & making directories...
Moving libraries to their places...
**/root/.scripts/fix-opera.sh: line 126: /resources/widevine_config.json: No such file or directory**
Removing temporary files...

**Comment by Ld-Hagen** [comment]
Fixed, thanks
