### ISSUE TITLE
No such file or directory: Incorrect Path to Opera?

### ISSUE THREAD

**Issue by stanman29** [Ld-Hagen/fix-opera-linux-ffmpeg-widevine#23]
When I installed the fix for Opera One(version: 107.0.5045.15) on Ubuntu 20.04 LTS , I get this error install scripts:
START-OF-SCRIPT
Getting download links...
Downloading files...
/tmp/opera-fix/ffmpeg.zip       100%[=====================================================>]   4.97M  1.53MB/s    in 3.3s    
/tmp/opera-fix/widevine.zip     100%[=====================================================>]  13.28M  1.49MB/s    in 9.6s    
Extracting files...
Doing opera
Removing old libraries & making directories...
Moving libraries to their places...
/root/.scripts/fix-opera.sh: line 126: /usr/bin/resources/widevine_config.json: No such file or directory
Removing temporary files...
END-OF-SCRIPT

My install path is:
Install:	/snap/opera/289/usr/lib/x86_64-linux-gnu/opera
Is the snap install the problem?

System:Ubuntu Core 18 (x86_64; ubuntu:GNOME)
Chromium version:121.0.6167.140

Browser identification
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 OPR/107.0.0.0

**Comment by Ld-Hagen** [comment]
It doesn't work for snap or flatpak versions
