### ISSUE TITLE
Stopped working with Opera One(version: 111.0.5168.18)

### ISSUE THREAD

**Issue by mlekolak** [Ld-Hagen/fix-opera-linux-ffmpeg-widevine#27]
Hey,
Good job! Unfortunately the last update stopped working :( Can you take a look at it? In my case, version 111.0.5168.18 running on Fedora 40.

**Comment by antonsoroko** [comment]
same issue with 111.0.5168.18 (Chromium 125.0.6422.143) and ubuntu 24.04.

**Comment by felipeprado** [comment]
It happened to me, I also have opened a pull request but it was closed, but I solved this, open this file: scripts/fix-opera.sh

then, go to line 100 and change for this:

OPERA_DIR=$(dirname $(whereis opera | cut -d ' ' -f 3))/opera

Re-run fix-opera and it will works well!
