### ISSUE TITLE
Chromium version mismatch

### ISSUE THREAD

**Issue by Gaeldrin** [Ld-Hagen/fix-opera-linux-ffmpeg-widevine#29]
Hello, since about a month ago (specifically since the release of 0.91), there is a mismatch between Chromium versions. The version of Chromium in your ffmpeg is one major higher than what is used in Opera. For example now that new Opera 114 is available, it is built on Chromium 128 ([changelog](https://blogs.opera.com/desktop/2024/09/opera-114/)) but you released version 0.92.0 that is built for Chromium 129 ([1](https://github.com/Ld-Hagen/fix-opera-linux-ffmpeg-widevine/releases/tag/nwjs-ffmpeg-0.92.0), [2](https://nwjs.io/versions.json)).

Can you please verify what is going on?

**Comment by Ld-Hagen** [comment]
These versions have no backward compatibility issues, so there is no need to wait for new opera release

**Comment by Gaeldrin** [comment]
Oh, I see. In other words it is not some mistake, you made the release intentionally earlier because you knew there are no issues with it. Thanks for confirming it and thank you for your work, I'm closing this issue.
