### ISSUE TITLE
Different libffmpeg.so necessary on Pop_os + Opera

### ISSUE THREAD

**Issue by derjogi** [Ld-Hagen/fix-opera-linux-ffmpeg-widevine#30]
Hi, FYI: I've just tried your script, but it didn't fix it. Only after replacing the ffmpeg file with the one from [another source](https://github.com/nwjs-ffmpeg-prebuilt/nwjs-ffmpeg-prebuilt/releases) it worked.
Thanks for making the script available 🙏

**Comment by Ld-Hagen** [comment]
These files are equal
