### ISSUE TITLE
Crashes with Slimjet playing WAV files

### ISSUE THREAD

**Issue by Raymond01** [Ld-Hagen/fix-opera-linux-ffmpeg-widevine#7]
Linux Mint Cinnamon 64 bit 20.2 

downloaded slimjet 33 - slimjet_amd64.deb from https://www.slimjet.com/en/dlpage.php?update=1
downloaded 0.59.0-linux-x64.zip from https://github.com/Ld-Hagen/fix-opera-linux-ffmpeg-widevine/releases

installed slimjet from terminal using sudo dpkg -i slimjet_amd64.deb
per slimjet instructions unzipped ffmpeg and ran sudo cp libffmpeg.so /opt/slimjet/ 

slimjet 33 without ffmpeg plays wav files. with ffmpeg trying to play wav files comes back with Error code: SIGSEGV
it might do it on other pages that do not have wav files but have not done that much testing.

you could try it on the following site by playing the wav files
https://www.wavsource.com/movie_stars/cagney.htm
https://www.wavsource.com/

**Comment by Ld-Hagen** [comment]
It seems Slimjet 33 uses old Chromium version (94) try libffmpeg 0.58.0 or 0.57.1

**Comment by Raymond01** [comment]
libffmpeg 0.58.0 worked. Thanks.

**Comment by oliveselow** [comment]
> Linux Mint Cinnamon 64 bit 20.2
> 
> downloaded slimjet 33 - slimjet_amd64.deb from https://www.slimjet.com/en/dlpage.php?update=1 downloaded 0.59.0-linux-x64.zip from https://github.com/Ld-Hagen/fix-opera-linux-ffmpeg-widevine/releases
> 
> installed slimjet from terminal using sudo dpkg -i slimjet_amd64.deb per slimjet instructions unzipped ffmpeg and ran sudo cp libffmpeg.so /opt/slimjet/
> 
> slimjet 33 without ffmpeg plays wav files. with ffmpeg trying to play wav files comes back with Error code: SIGSEGV it might do it on other pages that do not have wav files but have not done that much testing.
> 
> you could try it on the following site by playing the wav files https://www.wavsource.com/movie_stars/cagney.htm https://www.wavsource.com/

**Comment by oliveselow** [comment]
> Linux Mint Cinnamon 64 bit 20.2
> 
> downloaded slimjet 33 - slimjet_amd64.deb from https://www.slimjet.com/en/dlpage.php?update=1 downloaded 0.59.0-linux-x64.zip from https://github.com/Ld-Hagen/fix-opera-linux-ffmpeg-widevine/releases
> 
> installed slimjet from terminal using sudo dpkg -i slimjet_amd64.deb per slimjet instructions unzipped ffmpeg and ran sudo cp libffmpeg.so /opt/slimjet/
> 
> slimjet 33 without ffmpeg plays wav files. with ffmpeg trying to play wav files comes back with Error code: SIGSEGV it might do it on other pages that do not have wav files but have not done that much testing.
> 
> you could try it on the following site by playing the wav files https://www.wavsource.com/movie_stars/cagney.htm https://www.wavsource.com/
