### ISSUE TITLE
Older version works fine with newer versions of Opera

### ISSUE THREAD

**Issue by grohan47** [Ld-Hagen/fix-opera-linux-ffmpeg-widevine#8]
I have an older copy of this script installed on my computer and it seems to work absolutely fine and not crash Opera at all. I am attaching a zip for you to examine and roll back changes.
[fix-opera-linux-ffmpeg-widevine.zip](https://github.com/Ld-Hagen/fix-opera-linux-ffmpeg-widevine/files/8531178/fix-opera-linux-ffmpeg-widevine.zip)
.

**Comment by Ld-Hagen** [comment]
Now it should work

**Comment by oliveselow** [comment]
> Now it should work. Usually Opera pushes new version to repository a week or two after release, but this time they've made immediately or only one day later for some reason/

**Comment by oliveselow** [comment]
> I have an older copy of this script installed on my computer and it seems to work absolutely fine and not crash Opera at all. I am attaching a zip for you to examine and roll back changes. [fix-opera-linux-ffmpeg-widevine.zip](https://github.com/Ld-Hagen/fix-opera-linux-ffmpeg-widevine/files/8531178/fix-opera-linux-ffmpeg-widevine.zip) .
