### ISSUE TITLE
Origin of libffmpeg.so?

### ISSUE THREAD

**Issue by ghandmann** [Ld-Hagen/fix-opera-linux-ffmpeg-widevine#9]
Hi there!

Nice script. But i was wondering from where the released `libffmpeg.so` files come from?

I don't want to accuse you of anything, but technically it could contain arbitrary code that is executed on my machine. So it would be nice if this repo would be more transparent.

**Comment by Ld-Hagen** [comment]
It's built from source using tool from https://github.com/nwjs-ffmpeg-prebuilt/nwjs-ffmpeg-prebuilt

**Comment by oliveselow** [comment]
> It's built from source using tool from https://github.com/nwjs-ffmpeg-prebuilt/nwjs-ffmpeg-prebuilt
